### Numpy

- Syntax:for importing function
- import packagename
- packagename.attribute
- packagename.function

In [1]:
import math
math.pi #pi is the attribute

3.141592653589793

In [2]:
math.pow(2,3) #pow() is the funcyion

8.0

In [3]:
import statistics

In [4]:
dir(statistics)

['Decimal',
 'Fraction',
 'StatisticsError',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_coerce',
 '_convert',
 '_counts',
 '_exact_ratio',
 '_fail_neg',
 '_find_lteq',
 '_find_rteq',
 '_isfinite',
 '_ss',
 '_sum',
 'bisect_left',
 'bisect_right',
 'collections',
 'groupby',
 'harmonic_mean',
 'math',
 'mean',
 'median',
 'median_grouped',
 'median_high',
 'median_low',
 'mode',
 'numbers',
 'pstdev',
 'pvariance',
 'stdev',
 'variance']

In [7]:
help(statistics.mean)

Help on function mean in module statistics:

mean(data)
    Return the sample arithmetic mean of data.
    
    >>> mean([1, 2, 3, 4, 4])
    2.8
    
    >>> from fractions import Fraction as F
    >>> mean([F(3, 7), F(1, 21), F(5, 3), F(1, 3)])
    Fraction(13, 21)
    
    >>> from decimal import Decimal as D
    >>> mean([D("0.5"), D("0.75"), D("0.625"), D("0.375")])
    Decimal('0.5625')
    
    If ``data`` is empty, StatisticsError will be raised.



In [10]:
statistics.mean([1,2,3,4])

2.5

In [12]:
statistics.median([1,2,3,4])

2.5

In [13]:
statistics.median([8,6,3,4]) # we have to arrange those values in ascending order or descending order

5.0

In [18]:
li=[8,6,3,4]
a=sorted(li,reverse=False)
(statistics.median(a))


5.0

In [21]:
li.sort()
statistics.median(li)

5.0

In [22]:
import statistics as st

In [26]:
st.mean([1,2])

1.5

In [27]:
from statistics import mean
mean([1,2])

1.5

In [28]:
help(mean)

Help on function mean in module statistics:

mean(data)
    Return the sample arithmetic mean of data.
    
    >>> mean([1, 2, 3, 4, 4])
    2.8
    
    >>> from fractions import Fraction as F
    >>> mean([F(3, 7), F(1, 21), F(5, 3), F(1, 3)])
    Fraction(13, 21)
    
    >>> from decimal import Decimal as D
    >>> mean([D("0.5"), D("0.75"), D("0.625"), D("0.375")])
    Decimal('0.5625')
    
    If ``data`` is empty, StatisticsError will be raised.



In [29]:
import numpy as np

In [34]:
arr1=np.array([1,23,45,67])
arr1

array([ 1, 23, 45, 67])

In [33]:
type(arr1)

numpy.ndarray

In [35]:
arr2 = np.array((2,3,4,5))
arr2

array([2, 3, 4, 5])

In [36]:
np.array(range(6,11))

array([ 6,  7,  8,  9, 10])

In [37]:
arr3 = np.arange(3,11,2) # starting value,ending value,step value,11 is exclusive

In [38]:
arr3

array([3, 5, 7, 9])

In [39]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.linspace(1,10,5) # including last value it will divides into equal parts

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [42]:
list(range(1.2,7.9))

TypeError: 'float' object cannot be interpreted as an integer

In [48]:
np.arange(2.5,9.5,0.5)

array([2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5,
       9. ])

In [49]:
np.linspace(2.5,5.5,6)

array([2.5, 3.1, 3.7, 4.3, 4.9, 5.5])

In [50]:
np.array([[1,2,3],[5,6,7]])

array([[1, 2, 3],
       [5, 6, 7]])

In [51]:
np.array([[1],[2],[3]])

array([[1],
       [2],
       [3]])

In [52]:
np.array(((1,2,3),(5,6,7)))

array([[1, 2, 3],
       [5, 6, 7]])

In [53]:
np.array([(1,2,3),(5,6,7)])

array([[1, 2, 3],
       [5, 6, 7]])

In [61]:
arr_2d=np.array(((1,2,3),[5,6,7]))
arr_2d

array([[1, 2, 3],
       [5, 6, 7]])

In [58]:
arr_3d=np.array([[[1,2,3],[5,6,7]],[[1,2,3],[5,6,7]]])
arr_3d

array([[[1, 2, 3],
        [5, 6, 7]],

       [[1, 2, 3],
        [5, 6, 7]]])

In [59]:
arr_3d.shape

(2, 2, 3)

In [62]:
arr_2d.shape

(2, 3)

In [63]:
arr_3d.ndim # dimensions

3

In [64]:
arr_2d.ndim

2

In [66]:
a = np.arange(10,20,3)
a

array([10, 13, 16, 19])

In [67]:
[i**(1/2) for i in range(10,20,3)]

[3.1622776601683795, 3.605551275463989, 4.0, 4.358898943540674]

In [68]:
a


array([10, 13, 16, 19])

In [69]:
a**(1/2) # by using numpy array

array([3.16227766, 3.60555128, 4.        , 4.35889894])

In [70]:
a+5

array([15, 18, 21, 24])

In [75]:
b=np.arange(1,12,3)
b

array([ 1,  4,  7, 10])

In [76]:
a + b

array([11, 17, 23, 29])

In [77]:
a * b

array([ 10,  52, 112, 190])

In [78]:
a % b

array([0, 1, 2, 9], dtype=int32)

In [79]:
np.add(a,b)

array([11, 17, 23, 29])

In [80]:
np.divide(a,b)

array([10.        ,  3.25      ,  2.28571429,  1.9       ])

In [81]:
np.multiply(a,b)

array([ 10,  52, 112, 190])

In [82]:
np.log(a)

array([2.30258509, 2.56494936, 2.77258872, 2.94443898])

In [83]:
np.exp(a)

array([2.20264658e+04, 4.42413392e+05, 8.88611052e+06, 1.78482301e+08])

In [85]:
np.power(a,2)

array([100, 169, 256, 361], dtype=int32)

In [92]:
np.power(10000,100000)

0

In [1]:
import numpy as np

In [5]:
np.power(6809875565243,345678234567890)

-58778246802307239

In [11]:
a=np.arange(10,20,5)
a

array([10, 15])

In [9]:
print(a.ndim)

1


In [10]:
print(a.shape)

(2,)


In [12]:
print(a.itemsize)

4


In [13]:
a.dtype

dtype('int32')

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
s=np.ones((2,3))
s

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
s=np.ones((2,3),dtype=int)
s

array([[1, 1, 1],
       [1, 1, 1]])

In [18]:
s.shape

(2, 3)

In [19]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

In [22]:
s1=np.zeros((2,3))
s1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
s2=np.eye((2))
s2

array([[1., 0.],
       [0., 1.]])

In [25]:
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    
    Returns
    -------
    I : ndarray of shape (N,M)
      An array where all elements are equal to zero, except for the `k`-th
      diagonal, whose values are equal to one.
    
    See Also
    -

In [28]:
help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C')
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, `None`, means
         `np.array(fill_value).dtype`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of `fill_value` with the given shape, dtype, and order.
    
    See Also
    --------
    full_like : Return a new array with shape of input filled with value.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    zeros : Return a new array setting values 

In [30]:
np.full((2,2),np.inf)

array([[inf, inf],
       [inf, inf]])

In [31]:
np.full((2,2),3)

array([[3, 3],
       [3, 3]])

In [32]:
s1.shape

(2, 3)

In [33]:
s1.size

6

In [34]:
s1.shape[0]

2

In [35]:
s1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
np.eye((10),k=1)

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [38]:
np.eye((10),k=7)

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
np.eye((10),k=-1)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])

In [40]:
np.eye((10),k=-5)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [41]:
np.eye((10),k=1,dtype=np.int)

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [42]:
np.random.random((6,2))

array([[0.76032085, 0.22665312],
       [0.90165325, 0.76809616],
       [0.72248969, 0.17022788],
       [0.74298074, 0.99781554],
       [0.34050848, 0.83991058],
       [0.6399381 , 0.62801359]])

In [45]:
np.random.rand(8)

array([0.56701686, 0.7420368 , 0.57577578, 0.58716373, 0.21180221,
       0.04161564, 0.20474104, 0.16608818])

In [46]:
np.random.rand(8,7)

array([[0.08710225, 0.25961241, 0.16437941, 0.85111697, 0.82984052,
        0.28050855, 0.33179288],
       [0.05741188, 0.35687796, 0.37363832, 0.65025259, 0.82041342,
        0.31870051, 0.7574457 ],
       [0.17702072, 0.3978401 , 0.63264123, 0.5087475 , 0.22242133,
        0.74473298, 0.10192688],
       [0.90956952, 0.67633985, 0.36783141, 0.82897338, 0.17089133,
        0.51831415, 0.61171989],
       [0.23829654, 0.43724697, 0.16357386, 0.2135473 , 0.93828162,
        0.17165538, 0.00896923],
       [0.39679913, 0.61921467, 0.04072384, 0.27682083, 0.87060605,
        0.97513935, 0.97717432],
       [0.94238612, 0.55291347, 0.29953243, 0.06614635, 0.99724051,
        0.9899232 , 0.09893678],
       [0.34936739, 0.1247851 , 0.2282611 , 0.49496035, 0.14186065,
        0.33761066, 0.82144462]])

In [48]:
np.random.rand(8,3,4)

array([[[9.21111630e-01, 4.14887721e-01, 7.55365308e-01, 4.24443247e-01],
        [6.96904328e-04, 4.76887136e-01, 8.85795628e-01, 9.43338688e-01],
        [6.80136811e-01, 6.92132776e-01, 6.63001045e-01, 2.73538676e-03]],

       [[5.71954633e-01, 7.61336431e-01, 2.18655639e-01, 5.37063363e-01],
        [7.86198376e-01, 4.49890256e-02, 7.08358409e-01, 8.25218345e-01],
        [1.99595949e-01, 5.83644352e-01, 7.63313441e-01, 6.14362835e-01]],

       [[8.98254594e-01, 3.44475002e-01, 3.66482760e-01, 2.82525687e-01],
        [6.10522363e-02, 2.84441610e-01, 9.49978534e-01, 6.54736052e-03],
        [7.78302122e-01, 8.47063391e-01, 5.63748695e-01, 6.96461946e-01]],

       [[2.41507559e-01, 7.80024590e-01, 4.30700704e-01, 9.60218808e-01],
        [9.03213232e-01, 9.96801572e-02, 1.21913497e-01, 1.32502225e-03],
        [5.66669761e-01, 3.85754693e-01, 4.73894004e-01, 1.69773169e-01]],

       [[8.95176126e-01, 3.51181416e-01, 3.87946350e-01, 6.18207400e-01],
        [7.14295803e-02, 9.232

In [51]:
a2=np.random.randint(200,700,(10,12))
a2

array([[616, 262, 553, 402, 672, 317, 550, 321, 284, 398, 639, 306],
       [550, 633, 356, 462, 264, 585, 679, 677, 599, 218, 223, 441],
       [293, 546, 430, 210, 464, 462, 355, 646, 241, 562, 258, 646],
       [686, 395, 602, 390, 470, 434, 287, 616, 478, 491, 335, 240],
       [368, 264, 352, 436, 462, 618, 384, 647, 351, 688, 537, 562],
       [562, 672, 315, 308, 218, 451, 361, 313, 595, 695, 271, 467],
       [446, 520, 438, 340, 402, 339, 559, 563, 360, 516, 434, 672],
       [223, 371, 273, 346, 542, 495, 420, 679, 463, 571, 526, 647],
       [360, 617, 329, 253, 567, 366, 405, 573, 200, 675, 375, 612],
       [590, 534, 537, 303, 369, 397, 628, 401, 341, 541, 410, 242]])

In [50]:
np.random.randn(2,3)

array([[ 0.44522169, -0.17910878,  0.98439314],
       [ 0.94709667,  0.22929722,  0.6236049 ]])

In [52]:
a2[0]

array([616, 262, 553, 402, 672, 317, 550, 321, 284, 398, 639, 306])

In [53]:
a2[5]

array([562, 672, 315, 308, 218, 451, 361, 313, 595, 695, 271, 467])

In [54]:
a2[0,0]

616

In [55]:
a2[0,5]

317

In [56]:
a2[[2,5,7]]

array([[293, 546, 430, 210, 464, 462, 355, 646, 241, 562, 258, 646],
       [562, 672, 315, 308, 218, 451, 361, 313, 595, 695, 271, 467],
       [223, 371, 273, 346, 542, 495, 420, 679, 463, 571, 526, 647]])

In [57]:
a2[0,[3,5,7,9]]

array([402, 317, 321, 398])

In [58]:
a2[0]

array([616, 262, 553, 402, 672, 317, 550, 321, 284, 398, 639, 306])

In [59]:
a2

array([[616, 262, 553, 402, 672, 317, 550, 321, 284, 398, 639, 306],
       [550, 633, 356, 462, 264, 585, 679, 677, 599, 218, 223, 441],
       [293, 546, 430, 210, 464, 462, 355, 646, 241, 562, 258, 646],
       [686, 395, 602, 390, 470, 434, 287, 616, 478, 491, 335, 240],
       [368, 264, 352, 436, 462, 618, 384, 647, 351, 688, 537, 562],
       [562, 672, 315, 308, 218, 451, 361, 313, 595, 695, 271, 467],
       [446, 520, 438, 340, 402, 339, 559, 563, 360, 516, 434, 672],
       [223, 371, 273, 346, 542, 495, 420, 679, 463, 571, 526, 647],
       [360, 617, 329, 253, 567, 366, 405, 573, 200, 675, 375, 612],
       [590, 534, 537, 303, 369, 397, 628, 401, 341, 541, 410, 242]])

In [60]:
a2[[0,3,4,5],[3,5,7,9]]

array([402, 434, 647, 695])

In [61]:
a2[:,3]

array([402, 462, 210, 390, 436, 308, 340, 346, 253, 303])

In [62]:
a2[:,[2,3]]

array([[553, 402],
       [356, 462],
       [430, 210],
       [602, 390],
       [352, 436],
       [315, 308],
       [438, 340],
       [273, 346],
       [329, 253],
       [537, 303]])

In [63]:
a2[2:5,3]

array([210, 390, 436])

In [65]:
a2[2,:]

array([293, 546, 430, 210, 464, 462, 355, 646, 241, 562, 258, 646])

In [67]:
a2[2:,]

array([[293, 546, 430, 210, 464, 462, 355, 646, 241, 562, 258, 646],
       [686, 395, 602, 390, 470, 434, 287, 616, 478, 491, 335, 240],
       [368, 264, 352, 436, 462, 618, 384, 647, 351, 688, 537, 562],
       [562, 672, 315, 308, 218, 451, 361, 313, 595, 695, 271, 467],
       [446, 520, 438, 340, 402, 339, 559, 563, 360, 516, 434, 672],
       [223, 371, 273, 346, 542, 495, 420, 679, 463, 571, 526, 647],
       [360, 617, 329, 253, 567, 366, 405, 573, 200, 675, 375, 612],
       [590, 534, 537, 303, 369, 397, 628, 401, 341, 541, 410, 242]])

In [68]:
a2[0,0]

616

In [69]:
a2[8,8]

200

In [70]:
a2[2:5,3]

array([210, 390, 436])

In [71]:
a2[3,5:7]

array([434, 287])

- Fancy Indexing
- Broad casting
- Manipulating arrays 
 

In [1]:
import numpy as np

In [3]:
a = np.arange(5,100,7)
a

array([ 5, 12, 19, 26, 33, 40, 47, 54, 61, 68, 75, 82, 89, 96])

In [4]:
a.size

14

In [5]:
a%2 == 0 # Using bollean indexing is known as fancy indexing

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True])

In [7]:
a[[1,3,4]]

array([12, 26, 33])

In [8]:
a[[a%2 == 0]]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


array([12, 26, 40, 54, 68, 82, 96])

In [9]:
a[[a % 2 == 1]]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


array([ 5, 19, 33, 47, 61, 75, 89])

In [10]:
a[a > 15]

array([19, 26, 33, 40, 47, 54, 61, 68, 75, 82, 89, 96])

In [11]:
a * 2

array([ 10,  24,  38,  52,  66,  80,  94, 108, 122, 136, 150, 164, 178,
       192])

In [12]:
a1 = np.array([[1,2,3],[7,8,9]])

In [13]:
a1 * 2

array([[ 2,  4,  6],
       [14, 16, 18]])

In [14]:
a1 * np.array([[2],[3]])

array([[ 2,  4,  6],
       [21, 24, 27]])

In [16]:
a2 = np.array([[2],[3]])
a2

array([[2],
       [3]])

In [17]:
a1 + a2

array([[ 3,  4,  5],
       [10, 11, 12]])

In [18]:
a1 * a2

array([[ 2,  4,  6],
       [21, 24, 27]])

In [19]:
a1.ndim,a2.ndim

(2, 2)

In [20]:
a1.shape,a2.shape

((2, 3), (2, 1))

In [21]:
a1

array([[1, 2, 3],
       [7, 8, 9]])

In [22]:
a2

array([[2],
       [3]])

In [23]:
a3 = np.array([5,2])

In [24]:
a3

array([5, 2])

In [29]:
a3.shape,a2.shape

((2,), (2, 1))

In [28]:
a2 * a3

array([[10,  4],
       [15,  6]])

In [30]:
a4 = np.array([2,3,4])
a4

array([2, 3, 4])

In [31]:
a4.shape,a2.shape

((3,), (2, 1))

In [32]:
a4 * a2

array([[ 4,  6,  8],
       [ 6,  9, 12]])

In [33]:
a4 * a1

array([[ 2,  6, 12],
       [14, 24, 36]])

In [34]:
a3 * a1 # broadcasting is no applied because,the shapes are equal and it is not equal to one 

ValueError: operands could not be broadcast together with shapes (2,) (2,3) 

In [35]:
np.arange(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [38]:
np.arange(24).reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [39]:
np.arange(24).reshape(3,2,2)

ValueError: cannot reshape array of size 24 into shape (3,2,2)

In [40]:
np.arange(24).reshape(3,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [41]:
np.arange(24).reshape(6,-1) # -1 will generate how many rows and columns are available

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [42]:
np.arange(24).reshape(-1,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [44]:
np.arange(24).reshape(6,4,-1)

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]],

       [[12],
        [13],
        [14],
        [15]],

       [[16],
        [17],
        [18],
        [19]],

       [[20],
        [21],
        [22],
        [23]]])

In [47]:
np.linspace(23,45,25)

array([23.        , 23.91666667, 24.83333333, 25.75      , 26.66666667,
       27.58333333, 28.5       , 29.41666667, 30.33333333, 31.25      ,
       32.16666667, 33.08333333, 34.        , 34.91666667, 35.83333333,
       36.75      , 37.66666667, 38.58333333, 39.5       , 40.41666667,
       41.33333333, 42.25      , 43.16666667, 44.08333333, 45.        ])

In [50]:
a6 = np.linspace(23,45,25).reshape(5,-1)
a6

array([[23.        , 23.91666667, 24.83333333, 25.75      , 26.66666667],
       [27.58333333, 28.5       , 29.41666667, 30.33333333, 31.25      ],
       [32.16666667, 33.08333333, 34.        , 34.91666667, 35.83333333],
       [36.75      , 37.66666667, 38.58333333, 39.5       , 40.41666667],
       [41.33333333, 42.25      , 43.16666667, 44.08333333, 45.        ]])

In [51]:
a6.shape

(5, 5)

In [54]:
a6.reshape(1,-1)

array([[23.        , 23.91666667, 24.83333333, 25.75      , 26.66666667,
        27.58333333, 28.5       , 29.41666667, 30.33333333, 31.25      ,
        32.16666667, 33.08333333, 34.        , 34.91666667, 35.83333333,
        36.75      , 37.66666667, 38.58333333, 39.5       , 40.41666667,
        41.33333333, 42.25      , 43.16666667, 44.08333333, 45.        ]])

In [55]:
a6.reshape(1,-1)[0]

array([23.        , 23.91666667, 24.83333333, 25.75      , 26.66666667,
       27.58333333, 28.5       , 29.41666667, 30.33333333, 31.25      ,
       32.16666667, 33.08333333, 34.        , 34.91666667, 35.83333333,
       36.75      , 37.66666667, 38.58333333, 39.5       , 40.41666667,
       41.33333333, 42.25      , 43.16666667, 44.08333333, 45.        ])

In [56]:
a6.reshape(1,-1)[0][0]

23.0

In [57]:
a6.reshape(1,-1).shape

(1, 25)

In [58]:
a6.flatten()

array([23.        , 23.91666667, 24.83333333, 25.75      , 26.66666667,
       27.58333333, 28.5       , 29.41666667, 30.33333333, 31.25      ,
       32.16666667, 33.08333333, 34.        , 34.91666667, 35.83333333,
       36.75      , 37.66666667, 38.58333333, 39.5       , 40.41666667,
       41.33333333, 42.25      , 43.16666667, 44.08333333, 45.        ])

In [59]:
a = np.array([[1,2,3],[5,6,7]])

In [60]:
a

array([[1, 2, 3],
       [5, 6, 7]])

In [62]:
a.shape

(2, 3)

In [63]:
a.flatten()

array([1, 2, 3, 5, 6, 7])

In [64]:
a6.reshape(25,-1)

array([[23.        ],
       [23.91666667],
       [24.83333333],
       [25.75      ],
       [26.66666667],
       [27.58333333],
       [28.5       ],
       [29.41666667],
       [30.33333333],
       [31.25      ],
       [32.16666667],
       [33.08333333],
       [34.        ],
       [34.91666667],
       [35.83333333],
       [36.75      ],
       [37.66666667],
       [38.58333333],
       [39.5       ],
       [40.41666667],
       [41.33333333],
       [42.25      ],
       [43.16666667],
       [44.08333333],
       [45.        ]])

In [66]:
a6.reshape(-1,1)

array([[23.        ],
       [23.91666667],
       [24.83333333],
       [25.75      ],
       [26.66666667],
       [27.58333333],
       [28.5       ],
       [29.41666667],
       [30.33333333],
       [31.25      ],
       [32.16666667],
       [33.08333333],
       [34.        ],
       [34.91666667],
       [35.83333333],
       [36.75      ],
       [37.66666667],
       [38.58333333],
       [39.5       ],
       [40.41666667],
       [41.33333333],
       [42.25      ],
       [43.16666667],
       [44.08333333],
       [45.        ]])

In [68]:
np.expand_dims(a6.reshape(25),1)

array([[23.        ],
       [23.91666667],
       [24.83333333],
       [25.75      ],
       [26.66666667],
       [27.58333333],
       [28.5       ],
       [29.41666667],
       [30.33333333],
       [31.25      ],
       [32.16666667],
       [33.08333333],
       [34.        ],
       [34.91666667],
       [35.83333333],
       [36.75      ],
       [37.66666667],
       [38.58333333],
       [39.5       ],
       [40.41666667],
       [41.33333333],
       [42.25      ],
       [43.16666667],
       [44.08333333],
       [45.        ]])

In [70]:
np.expand_dims(np.arange(25),1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [71]:
np.expand_dims(np.arange(25),1).squeeze()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [72]:
a1 = np.array([[2,3],[5,6]])
a1

array([[2, 3],
       [5, 6]])

In [73]:
a2 = np.array([7,8])
a2

array([7, 8])

In [75]:
np.vstack((a1,a2))

array([[2, 3],
       [5, 6],
       [7, 8]])

In [76]:
a2 = np.array([[7,8],[9,0]])
a2

array([[7, 8],
       [9, 0]])

In [77]:
np.vstack((a1,a2))

array([[2, 3],
       [5, 6],
       [7, 8],
       [9, 0]])

In [78]:
a1

array([[2, 3],
       [5, 6]])

In [79]:
a2

array([[7, 8],
       [9, 0]])

In [80]:
np.hstack((a1,a2))

array([[2, 3, 7, 8],
       [5, 6, 9, 0]])

In [81]:
# Concatenate,stack

In [82]:
a

array([[1, 2, 3],
       [5, 6, 7]])

In [88]:
a = np.arange(10,40,2)

In [89]:
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [91]:
a.mean()

24.0

In [93]:
np.median(a)

24.0

In [94]:
a7 = np.random.randint(5,100,14)

In [95]:
a7

array([36, 86, 42, 54, 41, 66, 95, 78, 66, 51, 96, 29, 12, 52])

In [96]:
np.mean(a7)

57.42857142857143

In [98]:
np.median(a7)

53.0

In [101]:
res = np.sort(a7)
res

array([12, 29, 36, 41, 42, 51, 52, 54, 66, 66, 78, 86, 95, 96])

In [103]:
(res[6] + res[7])/2 # medain

53.0

In [104]:
np.quantile(a7,0.5)

53.0

In [105]:
np.quantile(a7,0.25)

41.25

In [108]:
np.median(np.sort(a7[:6]))

48.0

### 9th october 2019

- Trignomertic Functions
- Logarithemic
- Eponential
- Linear Algebra
- Matrix
- how to read as numpy array

In [2]:
import numpy as np
np.tan(45)

1.6197751905438615

In [3]:
np.tan(np.pi/4)

0.9999999999999999

In [4]:
import math
math.tan(np.pi/4)

0.9999999999999999

In [5]:
np.tan(np.arange(6))

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501])

In [8]:
a = np.random.random(5)
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[0.20686734 0.21391885 0.08851314 0.53819175 0.75575917]
[0.978369   0.97685143 0.99607501 0.84282243 0.65484966]
[0.21144102 0.21898811 0.08886193 0.63855888 1.15409568]


In [9]:
np.rad2deg(np.pi/4)

45.0

In [10]:
print(np.arctan(0.9999))

0.785348160897365


In [11]:
np.pi/4

0.7853981633974483

In [12]:
print(np.arccos(1))

0.0


In [13]:
print(np.sinh(a))

[0.2098831  0.21725876 0.08874521 0.59937648 0.96556373]


In [14]:
print(np.arcsinh(a)) # inverse hyperbolic

[0.20689279 0.21394896 0.08851351 0.54144449 0.77641954]


In [15]:
a1 = np.arange(2,16,2)
print(np.log(a1))
print(np.log2(a1))
print(np.log1p(a1))

[0.69314718 1.38629436 1.79175947 2.07944154 2.30258509 2.48490665
 2.63905733]
[1.         2.         2.5849625  3.         3.32192809 3.5849625
 3.80735492]
[1.09861229 1.60943791 1.94591015 2.19722458 2.39789527 2.56494936
 2.7080502 ]


In [16]:
a1

array([ 2,  4,  6,  8, 10, 12, 14])

In [17]:
np.log(3)

1.0986122886681098

In [18]:
np.log1p(2) #log(1+x)

1.0986122886681098

In [20]:
np.exp(a1)

array([7.38905610e+00, 5.45981500e+01, 4.03428793e+02, 2.98095799e+03,
       2.20264658e+04, 1.62754791e+05, 1.20260428e+06])

In [21]:
np.exp2(a)

array([1.15538362, 1.16117461, 1.06335928, 1.4827652 , 1.81103276])

In [26]:
np.expm1(a1)

array([6.38905610e+00, 5.35981500e+01, 4.02428793e+02, 2.97995799e+03,
       2.20254658e+04, 1.62753791e+05, 1.20260328e+06])

In [25]:
np.exp(2)-1

6.38905609893065

In [23]:
help(np.expm1)

Help on ufunc object:

expm1 = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array