### Python Libraries For Data Science
- Data science is the process of deriving knowledge and insights from a huge and diverse set of data through organizing, processing and analysing the data.
- There are nearly 20 python libraries for Data Science. Top five python libraries are
- TensorFlow
- NumPy
- SciPy
- Pandas
- Matplotlib
- In those libraries, Numpy and Pandas are the first choice to the data scientists who are aware of the technologies.

### NumPy: (Numerical Python)
- Numpy is Base N-Dimensional Array Package, is a python library and a fundamental
package for scientific computing in Python. It is used to create multidimensional arrays
- for fast operations. Use the following import conversion.
- import numpy as np

### Introduction to NumPy
- The learning objectives of this section are:
- Understand advantages of vectorised code using NumPy (over standard python ways)
- Create NumPy arrays
- Convert lists and tuples to NumPy arrays
- Create (initialise) arrays
- Inspect the structure and content of arrays
- Subset, slice, index and iterate through arrays
- Compare computation times in NumPy and standard Python lists

### NumPy Arrays
- NumPy have a fixed size of arrays used to store a collection of elements, unlike
- python lists. There are three types of arrays called 1D, 2D and 3D arrays.

### Advantages of NumPy
- We can write Vectorised code on numpy arrays, not on lists, which is convenient to read and write.
- Vectorized code typically does not contain explicit looping and indexing etc.
- Numpy is much faster than the standard python ways to do computations

In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(3,)

In [6]:
a1 = np.array([[1,2,3],[5,6,7]])

In [7]:
a1

array([[1, 2, 3],
       [5, 6, 7]])

In [8]:
type((a1))

numpy.ndarray

In [9]:
a1.shape

(2, 3)

In [10]:
a3 = np.array([[[1],[2],[4]]])

In [11]:
a3

array([[[1],
        [2],
        [4]]])

In [12]:
a3.shape

(1, 3, 1)

In [23]:
l = [1,2,3]
lam = lambda x : x**2
list(map(lam,l))

[1, 4, 9]

In [28]:
[i**2 for i in l]

[1, 4, 9]

In [30]:
l1 = np.array([1,2,3])

In [31]:
l1**2

array([1, 4, 9], dtype=int32)

In [32]:
l1*5

array([ 5, 10, 15])

In [33]:
l2 = np.array([2,3,4])

In [34]:
l1+l2

array([3, 5, 7])

In [40]:
a=range(2)
type(a)
a

range(0, 2)

In [41]:
b = np.arange(2)
type(b)
b

array([0, 1])

In [45]:
c = np.array(range(89))
type(c)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88])

In [46]:
np.arange(1,10,3)

array([1, 4, 7])

In [47]:
np.linspace(1,10,2)

array([ 1., 10.])

In [48]:
range(1.2,3.5)

TypeError: 'float' object cannot be interpreted as an integer

In [49]:
np.linspace(1,2.3,10)

array([1.        , 1.14444444, 1.28888889, 1.43333333, 1.57777778,
       1.72222222, 1.86666667, 2.01111111, 2.15555556, 2.3       ])

In [62]:
a= np.linspace(1,2.3,10)
type(a[0])

numpy.float64

In [63]:
arr_3d=np.array([[[1,2,3],[5,6,7]],[[1,2,3],[5,6,7]]])
arr_3d

array([[[1, 2, 3],
        [5, 6, 7]],

       [[1, 2, 3],
        [5, 6, 7]]])

In [78]:
a = arr_3d.reshape(4,-1)
a

array([[1, 2, 3],
       [5, 6, 7],
       [1, 2, 3],
       [5, 6, 7]])

In [74]:
arr_3d[:1]

array([[[1, 2, 3],
        [5, 6, 7]]])

In [80]:
a[[1,2]]

array([[5, 6, 7],
       [1, 2, 3]])

In [81]:
a[1:]

array([[5, 6, 7],
       [1, 2, 3],
       [5, 6, 7]])

In [82]:
a[1][0]

5

In [84]:
a[2][2]

3

In [85]:
a.ndim

2

In [86]:
a3.ndim

3

In [91]:
np.ones((1,2),dtype=int)

array([[1, 1]])

In [92]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [98]:
s= np.eye((2),dtype=int)
s

array([[1, 0],
       [0, 1]])

In [99]:
s.itemsize

4

In [101]:
np.full((2,3),4)

array([[4, 4, 4],
       [4, 4, 4]])

In [102]:
np.eye((10),k=1)

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [103]:
np.eye((10),k=-5)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [104]:
np.eye((10),k=6)

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [106]:
np.random.random((2,3))

array([[0.27601154, 0.6983628 , 0.44630177],
       [0.10525414, 0.00188961, 0.9512157 ]])

In [110]:
np.random.randint(10,200,(24,3))

array([[123, 192,  55],
       [157,  95,  61],
       [ 92, 185,  78],
       [142,  87, 188],
       [139, 143,  53],
       [145,  46,  34],
       [ 70, 110, 124],
       [140,  53, 175],
       [ 16,  30,  16],
       [ 57,  35, 196],
       [161, 142, 116],
       [152, 182, 132],
       [171, 144,  83],
       [ 69,  65,  62],
       [104,  32, 161],
       [ 99,  63,  29],
       [ 27,  75, 136],
       [175, 116, 105],
       [127, 183,  59],
       [131, 160, 105],
       [ 50,  90, 197],
       [174, 173, 125],
       [119,  19, 138],
       [101,  83,  14]])

In [112]:
np.random.rand(2,3)

array([[0.83290401, 0.93157758, 0.18765676],
       [0.43277353, 0.22741666, 0.28120065]])

In [113]:
np.tile([5],[2,3])

array([[5, 5, 5],
       [5, 5, 5]])

In [116]:
np.arange(10).reshape(2,5,1)

array([[[0],
        [1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8],
        [9]]])

In [117]:
a = np.array([1,2,3])

array([1, 2, 3])

In [118]:
a.size

12

In [120]:
a.itemsize

4

In [121]:
a.dtype

dtype('int32')

In [122]:
a.ndim

2

In [123]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.23606798, 2.44948974, 2.64575131],
       [1.        , 1.41421356, 1.73205081],
       [2.23606798, 2.44948974, 2.64575131]])

In [124]:
a

array([[1, 2, 3],
       [5, 6, 7],
       [1, 2, 3],
       [5, 6, 7]])

In [125]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.84147098,  0.90929743,  0.14112001],
       [-0.95892427, -0.2794155 ,  0.6569866 ]])

In [127]:
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [-3.38051501, -0.29100619,  0.87144798],
       [ 1.55740772, -2.18503986, -0.14254654],
       [-3.38051501, -0.29100619,  0.87144798]])

In [132]:
np.exp(a)

array([[   2.71828183,    7.3890561 ,   20.08553692],
       [ 148.4131591 ,  403.42879349, 1096.63315843],
       [   2.71828183,    7.3890561 ,   20.08553692],
       [ 148.4131591 ,  403.42879349, 1096.63315843]])

In [133]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.60943791, 1.79175947, 1.94591015],
       [0.        , 0.69314718, 1.09861229],
       [1.60943791, 1.79175947, 1.94591015]])

In [136]:
a1 = np.array([[1,2],[3,4]])
a1

array([[1, 2],
       [3, 4]])

In [137]:
np.linalg.det(a1)

-2.0000000000000004

In [138]:
np.linalg.inv(a1)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [139]:
np.linalg.eig(a1)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [140]:
a1

array([[1, 2],
       [3, 4]])

In [141]:
a1.T

array([[1, 3],
       [2, 4]])

In [142]:
a1

array([[1, 2],
       [3, 4]])

In [143]:
a2 = np.array([[2,3],[8,9]])
a2

array([[2, 3],
       [8, 9]])

In [144]:
a1*a2

array([[ 2,  6],
       [24, 36]])

In [145]:
a1+a2

array([[ 3,  5],
       [11, 13]])

In [146]:
np.dot(a1,a2)

array([[18, 21],
       [38, 45]])

In [148]:
a2


array([[2, 3],
       [8, 9]])

In [149]:
a1

array([[1, 2],
       [3, 4]])

In [150]:
a1.flatten()

array([1, 2, 3, 4])

In [151]:
a1

array([[1, 2],
       [3, 4]])

In [152]:
a2

array([[2, 3],
       [8, 9]])

In [153]:
a1.dot(a2)

array([[18, 21],
       [38, 45]])