## Numpy

-  Numerical Python, popularly known as Numpy has been designed to carry out mathematical computations at a faster and easier rate. 
- Numpy provides a large library of high level mathematical functions to operate on these structures.
- data structures like multi dimensional arrays beyond matrices and linear arrays. 

- In command line            
    - pip install numpy 
- Anaconda distribution            
    - conda install numpy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


- General Programming Concepts
    - Data Types, Type Conversion, Operators
    - Conditional Statements and Loops
    - Lists, Tuples, Sets, Dictionaries
    - Functions
    - OOPs in Python
    - Functional Programming i.e. List, Set and Dictionary Comprehensions

- If we are going to work on Data Fields like
    - Data Analytics
    - Machine Learning
    - AI
    - Deep Learning
    - Field in Data

- Important Packages for those fields
- Numpy --> Mathematical Analysis
- Pandas --> Data Analysis, Cleaning, Visualizations
- Matplotlib --> Powerful Visualiation Package

In [99]:
import numpy as np

In [3]:
np.__version__

'1.16.2'

In [5]:
li = [1,2,3]
print(type(li))

<class 'list'>


In [6]:
arr = np.array([1,2,2])
type(arr)

numpy.ndarray

In [7]:
arr.ndim

1

In [8]:
arr.dtype

dtype('int32')

In [11]:
arr1 = np.array([1,2,2,2.3,"alekhya"])
type(arr)

numpy.ndarray

In [12]:
arr1.dtype

dtype('<U32')

In [13]:
arr3 = np.array("24-07-20200")
arr3.dtype

dtype('<U11')

- 'b' − boolean
- 'i' − (signed) integer
- 'u' − unsigned integer
- 'f' − floating-point
- 'c' − complex-floating point
- 'm' − timedelta
- 'M' − datetime
- 'O' − (Python) objects
- 'S', 'a' − (byte-)string
- 'U' − Unicode
- 'V' − raw data (void)

In [14]:
a = np.array(3+2j)
a.dtype

dtype('complex128')

In [16]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(1,10.5)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
range(1,10.5)

TypeError: 'float' object cannot be interpreted as an integer

In [21]:
np.arange(1,10.5,1.2)

array([1. , 2.2, 3.4, 4.6, 5.8, 7. , 8.2, 9.4])

In [23]:
f = np.arange(1,100,2)
f

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [24]:
f[1:20]

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
       37, 39])

In [25]:
f[8]

17

In [27]:
f.shape

(50,)

In [30]:
f.reshape(5,10)

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29, 31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49, 51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69, 71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89, 91, 93, 95, 97, 99]])

In [31]:
f.reshape(2,-1)

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31,
        33, 35, 37, 39, 41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81,
        83, 85, 87, 89, 91, 93, 95, 97, 99]])

In [34]:
f.reshape(-1,4)

ValueError: cannot reshape array of size 50 into shape (4)

In [35]:
f1 = f.reshape(-1,5)
f1

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [36]:
f1.shape

(10, 5)

In [37]:
f1.ndim

2

In [41]:
arr4 = np.arange(0,20).reshape(2,2,5)
arr4

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [42]:
arr4.ndim

3

In [47]:
arr = arr4.reshape(-1,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [48]:
arr.ndim

2

In [50]:
li = [1,2,3]
l = []
for i in li:
    l.append(i+2)
print(l)

[3, 4, 5]


In [51]:
ar = np.array([2,3,4,5])
ar+2

array([4, 5, 6, 7])

In [52]:
ar*2

array([ 4,  6,  8, 10])

In [53]:
ar-2

array([0, 1, 2, 3])

In [54]:
ar = np.arange(1,10)
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
ar>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [56]:
ar[ar>5]

array([6, 7, 8, 9])

In [57]:
ar[ar%2==0]

array([2, 4, 6, 8])

- np.logical_and()
- np.logical_or()
- np.locical_not()

In [ ]:
divisible by 4 and 400
not divisible 100

In [58]:

years = np.arange(1900,2021)
print(years)


[1900 1901 1902 1903 1904 1905 1906 1907 1908 1909 1910 1911 1912 1913
 1914 1915 1916 1917 1918 1919 1920 1921 1922 1923 1924 1925 1926 1927
 1928 1929 1930 1931 1932 1933 1934 1935 1936 1937 1938 1939 1940 1941
 1942 1943 1944 1945 1946 1947 1948 1949 1950 1951 1952 1953 1954 1955
 1956 1957 1958 1959 1960 1961 1962 1963 1964 1965 1966 1967 1968 1969
 1970 1971 1972 1973 1974 1975 1976 1977 1978 1979 1980 1981 1982 1983
 1984 1985 1986 1987 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997
 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011
 2012 2013 2014 2015 2016 2017 2018 2019 2020]


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [66]:
a = np.logical_or(years%400 ==0,years%100!=0)
years[np.logical_and(a,years%4==0)]

array([1904, 1908, 1912, 1916, 1920, 1924, 1928, 1932, 1936, 1940, 1944,
       1948, 1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988,
       1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020])

In [68]:
zero = np.zeros(10)
print(zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [69]:

zero = np.zeros(10,dtype = int)
print(zero)

[0 0 0 0 0 0 0 0 0 0]


In [70]:
zero = np.zeros(10,dtype=object)
print(zero)

[0 0 0 0 0 0 0 0 0 0]


In [71]:
zero.dtype

dtype('O')

In [78]:
zero = np.ones((10,2),dtype=int)
print(zero)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [74]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [ ]:
Trignometric Methods


In [83]:
np.sin(90)

0.8939966636005579

In [88]:
np.sin(np.deg2rad(90))

1.0

np.sin(np.rad2deg(0.8939966636005579))

In [93]:
np.sinh(90)

6.102016471589204e+38

In [100]:
np1 = np.arange(100)

In [101]:
np1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [102]:
np.min(np1)

0

In [103]:
np.max(np1)

99

In [104]:
np.sum(np1)

4950

In [106]:
np.median(np1)

49.5

In [107]:
np.cumsum(np1)

array([   0,    1,    3,    6,   10,   15,   21,   28,   36,   45,   55,
         66,   78,   91,  105,  120,  136,  153,  171,  190,  210,  231,
        253,  276,  300,  325,  351,  378,  406,  435,  465,  496,  528,
        561,  595,  630,  666,  703,  741,  780,  820,  861,  903,  946,
        990, 1035, 1081, 1128, 1176, 1225, 1275, 1326, 1378, 1431, 1485,
       1540, 1596, 1653, 1711, 1770, 1830, 1891, 1953, 2016, 2080, 2145,
       2211, 2278, 2346, 2415, 2485, 2556, 2628, 2701, 2775, 2850, 2926,
       3003, 3081, 3160, 3240, 3321, 3403, 3486, 3570, 3655, 3741, 3828,
       3916, 4005, 4095, 4186, 4278, 4371, 4465, 4560, 4656, 4753, 4851,
       4950], dtype=int32)

In [108]:
np.cumprod(np1)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [ ]:
randomnunbers

In [109]:
np.random.randint(1,10)

7

In [111]:
np.random.random(10)

array([0.36118094, 0.78621888, 0.39536452, 0.61467524, 0.82216502,
       0.90774412, 0.35705067, 0.32152443, 0.80628251, 0.79780681])

In [112]:
np.random.randn(1,10)

array([[ 0.9290997 ,  1.54105019,  1.11413903,  0.58192096, -0.94772093,
         1.32370661,  0.23029205, -2.28049549, -0.33445111, -0.14213797]])

In [113]:
np.random.random_integers(1,5)

C:\Users\Alekhya\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  """Entry point for launching an IPython kernel.


3

In [118]:
a1 = np.arange(0,9).reshape(3,3)
print(a1.shape)
a1

(3, 3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [119]:
a2 = np.arange(9,18).reshape(3,3)
a2

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [116]:
a1*a2

array([[  0,  10,  22],
       [ 36,  52,  70],
       [ 90, 112, 136]])

In [120]:
a1.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [121]:
a1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [130]:
np.diagonal(a2)

array([ 9, 13, 17])

### Pandas

- Pandas mainly   used for Data Manipulation , Data Visuvalisation ,Data Cleaning
- used for adding, deleting, and modifying data in a database
- Data cleaning is the process of preparing data for analysis by removing or modifying data that is incorrect, incomplete, irrelevant, duplicated, or improperly formatted. 
- Data visualization is the graphic representation of data

- Data is stored in Two Ways or data Structure:
    - Series
    - DataFrame
- Series:
It is having only one column¶ and numbe rof rows

In [131]:
import pandas as pd

In [133]:
ser = pd.Series([10,20,30])
ser

0    10
1    20
2    30
dtype: int64

In [134]:
ser = pd.Series([10,20,30,"the"])
ser

0     10
1     20
2     30
3    the
dtype: object

In [135]:
ser[0]

10

In [136]:
ser[9]

KeyError: 9

In [138]:
ser[3]

'the'

In [139]:
ser1 = pd.Series(["alekhya","narmada","phani","subbareddy"],index=["ece","cse","eee","it"])
ser1

ece       alekhya
cse       narmada
eee         phani
it     subbareddy
dtype: object

In [140]:
ser1["ece"] # access the value based on index

'alekhya'

In [141]:
ser1.index[1] # to findout index

'cse'

In [147]:
ser1["cse"][3]

'm'

In [148]:

h = pd.Series({"name":"lakshmi","sal":35000,"desig":"Dev"})
h

name     lakshmi
sal        35000
desig        Dev
dtype: object

In [149]:
h["sal"]

35000

In [151]:
h.index

Index(['name', 'sal', 'desig'], dtype='object')

In [158]:
k = pd.Series(["Ranga","Srinu","Anil","Sastry","Ayyappa"],
              index=[1,"%",3," "," "])

In [159]:
k

1      Ranga
%      Srinu
3       Anil
      Sastry
     Ayyappa
dtype: object

In [160]:
k.index

Index([1, '%', 3, ' ', ' '], dtype='object')

In [161]:
k[" "]

      Sastry
     Ayyappa
dtype: object

In [162]:
g=pd.Series({"names":["vijay","lakshmi","raja"],
              "Sal":[25000,35000,45000],
             "Desig":["Dev","Trainer","texter"]})
g

names    [vijay, lakshmi, raja]
Sal       [25000, 35000, 45000]
Desig    [Dev, Trainer, texter]
dtype: object

In [165]:
g=pd.DataFrame({"names":["vijay","lakshmi","raja"],
              "Sal":[25000,35000,45000],
             "Desig":["Dev","Trainer","texter"]})
g

names    Sal    Desig
0    vijay  25000      Dev
1  lakshmi  35000  Trainer
2     raja  45000   texter

In [167]:
g.index

RangeIndex(start=0, stop=3, step=1)

In [169]:
g.columns

Index(['names', 'Sal', 'Desig'], dtype='object')

In [174]:
g.values

array([['vijay', 25000, 'Dev'],
       ['lakshmi', 35000, 'Trainer'],
       ['raja', 45000, 'texter']], dtype=object)

In [170]:
g["names"]

0      vijay
1    lakshmi
2       raja
Name: names, dtype: object

In [172]:
g["names"][1]

'lakshmi'

In [173]:
g["Sal"][1]

35000

In [175]:
g.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
names    3 non-null object
Sal      3 non-null int64
Desig    3 non-null object
dtypes: int64(1), object(2)
memory usage: 152.0+ bytes


In [176]:
g.describe()

Sal
count      3.0
mean   35000.0
std    10000.0
min    25000.0
25%    30000.0
50%    35000.0
75%    40000.0
max    45000.0

In [179]:
s = g[["names","Sal"]]
s

names    Sal
0    vijay  25000
1  lakshmi  35000
2     raja  45000

In [180]:
s.describe()

Sal
count      3.0
mean   35000.0
std    10000.0
min    25000.0
25%    30000.0
50%    35000.0
75%    40000.0
max    45000.0